[package]
name = "bitcoin-light-node"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.19", features = ["derive"] }
hyper = "1.4.1"
nakamoto = {version = "0.4.0"}
tokio = {version = "1.40.0", features = ["rt", "macros","rt-multi-thread"]}
